mutation CreateUploadSignedUrl($createUploadSignedUrlInput: CreateUploadSignedUrlInput!) {
  createUploadSignedUrl(createUploadSignedUrlInput: $createUploadSignedUrlInput) {
    signedUrl
    url
  }
}
